# Using state: merged

# Before state:
# -------------

# router-ios#show running-config | section ^hostname
# hostname Router

# Merged play:
# ------------
- name: Apply the provided configuration
  cisco.ios.ios_hostname:
  hosts: All
  tasks:
    - cisco.ios.ios_hostname:
       config:
        hostname: Switch
      state: merged
        var: ansible_facts
