---
- name: Change hostname
  hosts: all
  gather_facts: false
  
  tasks:
    - name: configure top level configuration
      config:
       hostname: RouterTesT
      state: overridden
  tasks:
    - name: Create Multiple VLANs
      ios_vlans:
        config:
          - name: vlan_101
            vlan_id: 101
          - name: vlan_102
            vlan_id: 102
          - name: vlan_103
            vlan_id: 103
        state: merged
      register: vln
- name: IOS Config Demo
  hosts: all

  tasks:
    - name: Configure Access
      ios_l2_interfaces:
        config:
          - name: Ethernet3/3
            access:
              vlan: 102
        state: merged
- name: Interface Configuration
  hosts: all
  tasks:
################### IP Config Merged ##############
    - name: Interface Configuration
      ios_l3_interfaces:
        config:
          - name: Ethernet3/2
            ipv4:
              - address: 2.2.2.5 255.255.255.0
        state: merged
      register: int

    - debug:
        var: int.before
    - debug:
        var: int.commands
    - debug:
        var: int.after        
