---
- name: Change hostname
  hosts: all
  gather_facts: false
  
  tasks:
    - name: configure top level configuration
      ios_config:
         lines: hostname Switch1
  tasks:
    - name: Create Multiple VLANs
      ios_vlans:
        config:
          - name: vlan_101
            vlan_id: 101
          - name: vlan_102
            vlan_id: 102
          - name: vlan_103
            vlan_id: 103
        state: merged
      register: vln
- name: IOS Config Demo
  hosts: all

  tasks:
    - name: Configure Access
      ios_l2_interfaces:
        config:
          - name: Ethernet3/3
            access:
              vlan: 102
        state: merged
