---
- name: Change hostname
  hosts: all
  gather_facts: false
  
  tasks:
    - name: configure top level configuration
      ios_config:
         lines: hostname Switch1

    - name: save running to start-config when modified
      ios_config:
        save_when: modified
